version: "3.9" # optional since v1.27.0
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Autograding
  client:
    build: ./client/
    container_name: grading-site-client
    ports:
      - "8081:8080"
    volumes:
      - ./client/:/app/
      - node_modules:/app/node_modules/
    environment:
      - CHOKIDAR_USEPOLLING=true
  server:
    build: ./server/
    container_name: grading-site-api
    # run database migrations and launch dev server
    command: ./startup_script.sh
    ports:
      - "5001:5000"
    volumes:
      - ./server/:/home/worker/code/
      - venv:/home/worker/code/venv/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=Autograding
      - POSTGRES_ADDRESS=postgres
      - MAIL_FROM_VAR=${MAIL_FROM_VAR}
      - MAIL_PASSWORD_VAR=${MAIL_PASSWORD_VAR}
      - MAIL_USERNAME_VAR=${MAIL_USERNAME_VAR}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    depends_on:
      - postgres
    ports:
      - "5050:80"

volumes:
  venv: {}
  node_modules: {}
