version: "3.9" # optional since v1.27.0
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  client:
    build: ./client/
    container_name: grading-site-client
    ports:
      - "8080:8080"
    volumes:
      - ./client/:/app/
      - node_modules:/app/node_modules/
    depends_on:
      - postgres
  server:
    build: ./server/
    container_name: grading-site-api
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/home/worker/code/
      - venv:/home/worker/code/venv/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_ADDRESS=${POSTGRES_ADDRESS}
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "5050:80"

volumes:
  venv: {}
  node_modules: {}
